"""Make transaction date non-nullable

Revision ID: 345d1a3c1c1b
Revises: 6dc029f3780a
Create Date: 2025-04-01 18:43:07.620450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345d1a3c1c1b'
down_revision = '6dc029f3780a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
