"""empty message

Revision ID: 6dc029f3780a
Revises: 5beca51e3974
Create Date: 2025-04-01 18:40:57.661357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dc029f3780a'
down_revision = '5beca51e3974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_constraint('unique_budget_per_category_month', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_budget_per_category_month', ['user_id', 'category', 'month', 'year'])

    # ### end Alembic commands ###
